/** Maps ingredient names (lowercase) to grocery categories. */
export const CATEGORY_MAP: Record<string, string> = {
  // Produce - Vegetables
  onion: 'produce',
  onions: 'produce',
  'red onion': 'produce',
  'yellow onion': 'produce',
  'white onion': 'produce',
  'green onion': 'produce',
  'green onions': 'produce',
  scallion: 'produce',
  scallions: 'produce',
  shallot: 'produce',
  shallots: 'produce',
  garlic: 'produce',
  ginger: 'produce',
  potato: 'produce',
  potatoes: 'produce',
  'sweet potato': 'produce',
  'sweet potatoes': 'produce',
  carrot: 'produce',
  carrots: 'produce',
  celery: 'produce',
  broccoli: 'produce',
  cauliflower: 'produce',
  spinach: 'produce',
  kale: 'produce',
  lettuce: 'produce',
  cabbage: 'produce',
  'bell pepper': 'produce',
  'bell peppers': 'produce',
  pepper: 'produce',
  peppers: 'produce',
  jalapeno: 'produce',
  jalapenos: 'produce',
  tomato: 'produce',
  tomatoes: 'produce',
  cucumber: 'produce',
  zucchini: 'produce',
  squash: 'produce',
  'butternut squash': 'produce',
  eggplant: 'produce',
  mushroom: 'produce',
  mushrooms: 'produce',
  corn: 'produce',
  peas: 'produce',
  'green beans': 'produce',
  asparagus: 'produce',
  'brussels sprouts': 'produce',
  artichoke: 'produce',
  beet: 'produce',
  beets: 'produce',
  radish: 'produce',
  turnip: 'produce',
  parsnip: 'produce',
  leek: 'produce',
  leeks: 'produce',
  avocado: 'produce',
  'baby spinach': 'produce',
  arugula: 'produce',
  'mixed greens': 'produce',
  bokchoy: 'produce',
  'snap peas': 'produce',
  edamame: 'produce',
  okra: 'produce',

  // Produce - Fruits
  lemon: 'produce',
  lemons: 'produce',
  lime: 'produce',
  limes: 'produce',
  orange: 'produce',
  oranges: 'produce',
  apple: 'produce',
  apples: 'produce',
  banana: 'produce',
  bananas: 'produce',
  strawberry: 'produce',
  strawberries: 'produce',
  blueberry: 'produce',
  blueberries: 'produce',
  raspberry: 'produce',
  raspberries: 'produce',
  blackberry: 'produce',
  blackberries: 'produce',
  mango: 'produce',
  pineapple: 'produce',
  peach: 'produce',
  peaches: 'produce',
  pear: 'produce',
  grape: 'produce',
  grapes: 'produce',
  cherry: 'produce',
  cherries: 'produce',
  cranberry: 'produce',
  cranberries: 'produce',
  coconut: 'produce',
  watermelon: 'produce',
  cantaloupe: 'produce',
  plum: 'produce',

  // Produce - Herbs
  basil: 'produce',
  cilantro: 'produce',
  parsley: 'produce',
  mint: 'produce',
  dill: 'produce',
  rosemary: 'produce',
  thyme: 'produce',
  sage: 'produce',
  oregano: 'produce',
  chives: 'produce',
  tarragon: 'produce',

  // Meat & Poultry
  chicken: 'meat',
  'chicken breast': 'meat',
  'chicken breasts': 'meat',
  'chicken thigh': 'meat',
  'chicken thighs': 'meat',
  'chicken drumstick': 'meat',
  'chicken drumsticks': 'meat',
  'ground chicken': 'meat',
  turkey: 'meat',
  'ground turkey': 'meat',
  beef: 'meat',
  'ground beef': 'meat',
  steak: 'meat',
  'beef stew meat': 'meat',
  'chuck roast': 'meat',
  pork: 'meat',
  'pork chop': 'meat',
  'pork chops': 'meat',
  'pork tenderloin': 'meat',
  'ground pork': 'meat',
  bacon: 'meat',
  sausage: 'meat',
  'italian sausage': 'meat',
  ham: 'meat',
  lamb: 'meat',
  'ground lamb': 'meat',
  prosciutto: 'meat',
  pancetta: 'meat',
  'hot dog': 'meat',
  pepperoni: 'meat',
  salami: 'meat',
  'deli meat': 'meat',

  // Seafood
  salmon: 'seafood',
  shrimp: 'seafood',
  tuna: 'seafood',
  cod: 'seafood',
  tilapia: 'seafood',
  halibut: 'seafood',
  mahi: 'seafood',
  crab: 'seafood',
  lobster: 'seafood',
  scallop: 'seafood',
  scallops: 'seafood',
  mussel: 'seafood',
  mussels: 'seafood',
  clam: 'seafood',
  clams: 'seafood',
  anchovy: 'seafood',
  anchovies: 'seafood',
  sardine: 'seafood',
  sardines: 'seafood',

  // Dairy
  milk: 'dairy',
  'whole milk': 'dairy',
  'skim milk': 'dairy',
  buttermilk: 'dairy',
  cream: 'dairy',
  'heavy cream': 'dairy',
  'whipping cream': 'dairy',
  'half and half': 'dairy',
  'sour cream': 'dairy',
  butter: 'dairy',
  'unsalted butter': 'dairy',
  'salted butter': 'dairy',
  egg: 'dairy',
  eggs: 'dairy',
  'egg yolk': 'dairy',
  'egg yolks': 'dairy',
  'egg white': 'dairy',
  'egg whites': 'dairy',
  cheese: 'dairy',
  'cheddar cheese': 'dairy',
  'mozzarella cheese': 'dairy',
  'parmesan cheese': 'dairy',
  parmesan: 'dairy',
  'cream cheese': 'dairy',
  'ricotta cheese': 'dairy',
  'goat cheese': 'dairy',
  'feta cheese': 'dairy',
  feta: 'dairy',
  'swiss cheese': 'dairy',
  'gruyere cheese': 'dairy',
  gruyere: 'dairy',
  yogurt: 'dairy',
  'greek yogurt': 'dairy',
  'cottage cheese': 'dairy',
  'heavy whipping cream': 'dairy',
  mascarpone: 'dairy',

  // Pantry - Oils & Vinegars
  'olive oil': 'pantry',
  'extra virgin olive oil': 'pantry',
  'vegetable oil': 'pantry',
  'canola oil': 'pantry',
  'coconut oil': 'pantry',
  'sesame oil': 'pantry',
  'avocado oil': 'pantry',
  vinegar: 'pantry',
  'white vinegar': 'pantry',
  'apple cider vinegar': 'pantry',
  'balsamic vinegar': 'pantry',
  'red wine vinegar': 'pantry',
  'rice vinegar': 'pantry',

  // Pantry - Sauces & Condiments
  'soy sauce': 'pantry',
  'fish sauce': 'pantry',
  'worcestershire sauce': 'pantry',
  'hot sauce': 'pantry',
  'tomato paste': 'pantry',
  'tomato sauce': 'pantry',
  ketchup: 'pantry',
  mustard: 'pantry',
  'dijon mustard': 'pantry',
  mayonnaise: 'pantry',
  'sriracha': 'pantry',
  'hoisin sauce': 'pantry',
  'oyster sauce': 'pantry',
  'barbecue sauce': 'pantry',
  'maple syrup': 'pantry',
  honey: 'pantry',
  molasses: 'pantry',

  // Pantry - Dry Goods
  flour: 'pantry',
  'all-purpose flour': 'pantry',
  'bread flour': 'pantry',
  'whole wheat flour': 'pantry',
  'almond flour': 'pantry',
  sugar: 'pantry',
  'brown sugar': 'pantry',
  'powdered sugar': 'pantry',
  'granulated sugar': 'pantry',
  'confectioners sugar': 'pantry',
  salt: 'pantry',
  'kosher salt': 'pantry',
  'sea salt': 'pantry',
  'black pepper': 'pantry',
  'baking powder': 'pantry',
  'baking soda': 'pantry',
  'vanilla extract': 'pantry',
  'vanilla': 'pantry',
  'cornstarch': 'pantry',
  'cocoa powder': 'pantry',
  'chocolate chips': 'pantry',
  'dark chocolate': 'pantry',
  yeast: 'pantry',
  'active dry yeast': 'pantry',
  'instant yeast': 'pantry',
  gelatin: 'pantry',
  breadcrumbs: 'pantry',
  'panko breadcrumbs': 'pantry',
  'panko': 'pantry',

  // Pantry - Spices
  'chili powder': 'spices',
  cumin: 'spices',
  'ground cumin': 'spices',
  paprika: 'spices',
  'smoked paprika': 'spices',
  cinnamon: 'spices',
  'ground cinnamon': 'spices',
  nutmeg: 'spices',
  'ground nutmeg': 'spices',
  'ground ginger': 'spices',
  turmeric: 'spices',
  cayenne: 'spices',
  'cayenne pepper': 'spices',
  'red pepper flakes': 'spices',
  'crushed red pepper': 'spices',
  'garlic powder': 'spices',
  'onion powder': 'spices',
  'italian seasoning': 'spices',
  'taco seasoning': 'spices',
  'bay leaf': 'spices',
  'bay leaves': 'spices',
  cloves: 'spices',
  'ground cloves': 'spices',
  allspice: 'spices',
  cardamom: 'spices',
  coriander: 'spices',
  'ground coriander': 'spices',
  'curry powder': 'spices',
  'garam masala': 'spices',
  'dried oregano': 'spices',
  'dried basil': 'spices',
  'dried thyme': 'spices',
  'dried rosemary': 'spices',
  'dried parsley': 'spices',
  saffron: 'spices',
  'five spice': 'spices',
  'white pepper': 'spices',
  'celery salt': 'spices',
  'mustard powder': 'spices',

  // Pantry - Grains & Pasta
  rice: 'pantry',
  'white rice': 'pantry',
  'brown rice': 'pantry',
  'jasmine rice': 'pantry',
  'basmati rice': 'pantry',
  pasta: 'pantry',
  spaghetti: 'pantry',
  penne: 'pantry',
  linguine: 'pantry',
  fettuccine: 'pantry',
  rigatoni: 'pantry',
  macaroni: 'pantry',
  'egg noodles': 'pantry',
  'rice noodles': 'pantry',
  quinoa: 'pantry',
  couscous: 'pantry',
  oats: 'pantry',
  'rolled oats': 'pantry',
  barley: 'pantry',
  polenta: 'pantry',
  tortilla: 'pantry',
  tortillas: 'pantry',
  'flour tortillas': 'pantry',
  'corn tortillas': 'pantry',
  'pita bread': 'pantry',
  'naan': 'pantry',
  bread: 'pantry',

  // Pantry - Canned Goods
  'canned tomatoes': 'pantry',
  'diced tomatoes': 'pantry',
  'crushed tomatoes': 'pantry',
  'canned beans': 'pantry',
  'black beans': 'pantry',
  'kidney beans': 'pantry',
  'cannellini beans': 'pantry',
  'chickpeas': 'pantry',
  'garbanzo beans': 'pantry',
  'lentils': 'pantry',
  'coconut milk': 'pantry',
  'chicken broth': 'pantry',
  'chicken stock': 'pantry',
  'beef broth': 'pantry',
  'beef stock': 'pantry',
  'vegetable broth': 'pantry',
  'vegetable stock': 'pantry',
  broth: 'pantry',
  stock: 'pantry',
  'canned tuna': 'pantry',
  'canned salmon': 'pantry',
  'pumpkin puree': 'pantry',
  'tomato soup': 'pantry',

  // Pantry - Nuts & Seeds
  almond: 'pantry',
  almonds: 'pantry',
  walnut: 'pantry',
  walnuts: 'pantry',
  pecan: 'pantry',
  pecans: 'pantry',
  peanut: 'pantry',
  peanuts: 'pantry',
  'pine nuts': 'pantry',
  cashew: 'pantry',
  cashews: 'pantry',
  pistachio: 'pantry',
  pistachios: 'pantry',
  'sesame seeds': 'pantry',
  'sunflower seeds': 'pantry',
  'chia seeds': 'pantry',
  'flax seeds': 'pantry',
  'peanut butter': 'pantry',
  'almond butter': 'pantry',
  tahini: 'pantry',

  // Frozen
  'frozen peas': 'frozen',
  'frozen corn': 'frozen',
  'frozen spinach': 'frozen',
  'frozen berries': 'frozen',
  'frozen strawberries': 'frozen',
  'ice cream': 'frozen',
  'puff pastry': 'frozen',
  'pie crust': 'frozen',

  // Beverages / Other
  wine: 'beverages',
  'white wine': 'beverages',
  'red wine': 'beverages',
  beer: 'beverages',
  coffee: 'beverages',
  tea: 'beverages',
  water: 'beverages',
}

/**
 * Look up the grocery category for an ingredient name.
 * Tries exact match first, then checks if any key is contained in the name.
 */
export function lookupCategory(ingredientName: string): string | null {
  const lower = ingredientName.toLowerCase().trim()

  // Exact match
  if (CATEGORY_MAP[lower]) return CATEGORY_MAP[lower]

  // Check if any known ingredient is a substring
  for (const [key, category] of Object.entries(CATEGORY_MAP)) {
    if (lower.includes(key)) return category
  }

  return null
}
